@id = f8b7fcb0-98c9-4ab5-bcb7-45f4f354916a

# @name addWorkReport
POST {{base-address}}/workreports/{{id}} HTTP/2.0
Content-Type: application/json

{
    "name": "name-{{$guid}}",
    "days": [
        "2021-12-31"
    ],
    "customerId": "{{customerId}}"
}

###

POST {{base-address}}/workreports/{{id}}/days HTTP/2.0
Content-Type: application/json

{
    "days": [
        "2021-12-31",
        "2022-12-31",
        "2021-12-22",
        "2011-12-22"
    ]
}

###

DELETE {{base-address}}/workreports/{{id}}/days HTTP/2.0
Content-Type: application/json

{
    "days": [
        "2021-12-31"
    ]
}

###

POST {{base-address}}/workreports/{{id}}/send HTTP/2.0
Content-Type: application/json

{
    "emailAddresses": [
        "toto@contoso.com",
        "titi@contoso.com"
    ]
}

###


POST {{base-address}}/workreports/{{id}}/customer HTTP/2.0
Content-Type: application/json

{
    "customerId": "{{customerId}}"
}

###

DELETE {{base-address}}/workreports/{{id}} HTTP/2.0

###

GET {{base-address}}/workreports/{{id}} HTTP/2.0

###

GET {{base-address}}/workreports HTTP/2.0

###

@customerId = a8b7fcb0-98c9-4ab5-bcb7-45f4f354916b

# @name addCustomer
POST {{base-address}}/customers/{{customerId}} HTTP/2.0
Content-Type: application/json

{
    "name": "name-{{$guid}}"
}

###

# @name removeCustomer
DELETE {{base-address}}/customers/{{customerId}} HTTP/2.0

###

GET {{base-address}}/customers HTTP/2.0