@id = f8b7fcb0-98c9-4ab5-bcb7-45f4f354916a

# @name addWorkReport
POST {{base-address}}/workreports/{{id}} HTTP/1.1
Content-Type: application/json

{
    "name": "name-{{$guid}}",
    "days": [
        "2021-12-31"
    ]
}

###

POST {{base-address}}/workreports/{{id}}/days HTTP/1.1
Content-Type: application/json

{
    "days": [
        "2021-12-31",
        "2022-12-31",
        "2021-12-22",
        "2011-12-22"
    ]
}

###

DELETE {{base-address}}/workreports/{{id}}/days HTTP/1.1
Content-Type: application/json

{
    "days": [
        "2021-12-31"
    ]
}

###

POST {{base-address}}/workreports/{{id}}/send HTTP/1.1
Content-Type: application/json

{
    "emailAddresses": [
        "toto@contoso.com",
        "titi@contoso.com"
    ]
}

###

DELETE {{base-address}}/workreports/{{id}} HTTP/1.1

###

GET {{base-address}}/workreports/{{id}} HTTP/1.1

###

GET {{base-address}}/workreports HTTP/1.1
